### ISSUE TITLE
Smooth tracking motion

### ISSUE THREAD

**Issue by jankansky** [weingrill/RoboTel#1]
Excellent project! I was very pleased to find this.  I have connected this code to a small telescope controlled by TwinCAT and CANOpen Cia402 drives (Technosoft iPOS4808-myCAN-STO).

When I enable "Track" mode, the code switches to using MC_ExtSetPointGenFeed to provide position, velocity, and acceleration values to the axes. It seems the velocity and acceleration demands in this mode are fixed values (velocity: 10.0, accel: 1.0), and only the position demand changes with time. With my motor controllers this doesn't result in smooth motion, and a lot of noise comes from the motors.

I'm wondering how to solve this easily. Perhaps the velocity and acceleration should be computed from derivatives of the desired trajectory. Your thoughts?

**Comment by weingrill** [comment]
Hi Jan,
thanks for your interest in this project. Be aware that the code was only intended and tested on Beckhoff AX5000 servo drives.
The usage of MC_ExtSetPointGenFeed is a rather delicate.  Usually a wrong set of PID parameters for the position and current controller is responsible for loud servo motors. There are currently three solutions for this problem, with which I am experimenting:

- usage of two different PID parameter sets for slewing and tracking
- calculation of analytical velocities (as done for the derotator)
- calculation of empirical velocities and accelerations as a time derivative of the (last) positions.

The first one requires writing of the SoE parameters from the runtime, which is doable, but risky. Setting wrong parameters might havoc the drive.
For the last two I have to note that the MC_ExtSetPointGenFeed seems to use the set velocity and acceleration values as upper limits for the position change.

**Comment by jankansky** [comment]
Thanks for the feedback. I just had success with your third option!  I compute the velocity and acceleration demands by saving the last three position demands (no noise in these) and on each step I compute the derivatives and pass the results into the MC_ExtSetPointGenFeed.

I removed the logic that uses (0.95 of the current position * 0.05 of the target position) to set the position demand. I didn't want the encoder noise in the current position to corrupt my velocity and acceleration derivatives. Since I removed this filtering, it is important that I trigger track mode directly after the slew finishes so that there isn't a large step in the telescope position on initiation of tracking.  I'm sure that could be handled in a better way.

I also worked with AX5000 drives in the past, and I do believe they respect the Velocity and Acceleration specified in the MC_ExtSetPointGenFeed, at least that is what our Beckhoff rep told me, and it seemed to work.

Jan

**Comment by weingrill** [comment]
Thanks for the hint. Is there any chance, you could send me the code snippet?

Jörg

**Comment by jankansky** [comment]
I added a few variables to FB_Axis2:

Velocity_demand:	LREAL := 0.0;
Acceleration_demand:	LREAL := 0.0;
Position_demand: LREAL := 0;
Position_step_minus1: LREAL := 0;
Position_step_minus2: LREAL := 0;
Velocity_step_minus1: LREAL := 0;


Then each iteration I do:

Position_demand := Position;

IF Position_demand > AbsolutePosition THEN
	Direction := -1;
ELSE
	Direction := 1;
END_IF

Velocity_demand := ABS(Position_demand - Position_step_minus1)/0.004;
Acceleration_demand := ABS(Velocity_demand - Velocity_step_minus1)/0.004;

IF Velocity_demand > 8.0 THEN
	Velocity_demand := 8.0;
END_IF

IF Acceleration_demand > 1.0 THEN
	Acceleration_demand := 1.0;
END_IF
	
MC_ExtSetPointGenFeed(
	Position :=		Position_demand,
	Velocity :=		Velocity_demand,
	Acceleration :=	Acceleration_demand,
	Direction :=	Direction, 
	Axis :=			AxisRef);

Position_step_minus2 := Position_step_minus1;
Position_step_minus1 := Position_demand;
Velocity_step_minus1 := Velocity_demand;

0.004 is my loop interval in seconds.  I haven't tested this rigorously, but the first attempt resulted in smooth tracking of the RA/Dec of an object.
Jan
